chore : 장고에 그라파나와 프로메테우스 연동
2023-Summer-Bootcamp-Team-B/Project pull request #40
Opened 2023-07-17 06:08 UTC by wjsqudtjs2

## 🛠️ 변경사항
장고에 그라파나, 프로메테우스 연동하려고 settings.py, urls.py, docker-compose.yml, prometheus.yml 설정음 조금 바꾸었습니다.

</br>
</br>

## ☝️ 유의사항

</br>
</br>

## 👀 참고자료
https://www.devkuma.com/docs/prometheus/docker-compose-install/
</br>
</br>

## ❗체크리스트
- [ ] 하나의 메소드는 최소의 기능만 하도록 설정했나요?
- [ ] 수정 가능하도록 유연하게 작성했나요?
- [ ] 필요 없는 import문이나 setter 등을 삭제했나요?
- [ ] 기존의 코드에 영향이 없는 것을 확인하였나요?

2023-07-17 08:13 UTC, Mayreeel requested changes
django-exporter 필요없으니 삭제 부탁 드려용

2023-07-17 17:52 UTC, Mayreeel requested changes
grafana.db 올리면 안될거같아요 대시보드 JSON으로 추출하거나 Grafana 구성 파일 추출해서 올려주세요

2023-07-18 01:46 UTC, wjsqudtjs2 commented
넵!

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23.
07. 18. 오전 10:46:00

2023년 7월 18일 (화) 오전 2:52, Kyu-hyun Lee ***@***.***>님이 작성:

> ***@***.**** requested changes on this pull request.
>
> grafana.db 올리면 안될거같아요 대시보드 JSON으로 추출하거나 Grafana 구성 파일 추출해서 올려주세요
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/2023-Summer-Bootcamp-Team-B/Project/pull/40#pullrequestreview-1533365104>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA3EOE2NDXW67XAJCH3PG5LXQV3VXANCNFSM6AAAAAA2MOXYMI>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-07-21 17:02 UTC, Mayreeel approved these changes
수고하셨습니다~~!!

2023-07-21 17:05 UTC, merged